# Google Cloud Run configuration file
# This is used for Cloud Run deployment

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: speech-memorization
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Allocate more CPU and memory for speech processing
        run.googleapis.com/cpu: "2"
        run.googleapis.com/memory: "4Gi"
        run.googleapis.com/max-scale: "10"
        run.googleapis.com/min-scale: "1"
        # Connection timeout for long speech processing requests
        run.googleapis.com/timeout: "300s"
        # Enable Cloud SQL connection
        run.googleapis.com/cloudsql-instances: "PROJECT_ID:REGION:INSTANCE_NAME"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      serviceAccountName: "speech-memorization-sa@PROJECT_ID.iam.gserviceaccount.com"
      containers:
      - image: gcr.io/PROJECT_ID/speech-memorization:latest
        ports:
        - containerPort: 8080
        env:
        - name: DEBUG
          value: "False"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: secret-key
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-config
              key: url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-config
              key: url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-config
              key: api-key
        - name: GOOGLE_CLOUD_PROJECT_ID
          value: "PROJECT_ID"
        - name: ALLOWED_HOSTS
          value: "*"
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5