runtime: python311

env_variables:
  DJANGO_SETTINGS_MODULE: speech_memorization.settings_cloud
  DEBUG: False
  GOOGLE_CLOUD_PROJECT_ID: serverless-test-12345
  ALLOWED_HOSTS: "*"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
# Static files
- url: /static
  static_dir: staticfiles
  secure: always

# Media files  
- url: /media
  static_dir: media
  secure: always

# All other URLs go to Django
- url: /.*
  script: auto
  secure: always

entrypoint: gunicorn speech_memorization.wsgi:application --bind :$PORT --workers 2 --timeout 120