# Cloud Run deployment configuration
runtime: python311

env_variables:
  DJANGO_SETTINGS_MODULE: "speech_memorization.settings_minimal"
  DEBUG: "True"
  ALLOWED_HOSTS: "speech-memorization-496146455129.us-central1.run.app,.run.app,*"

automatic_scaling:
  min_instances: 0
  max_instances: 3