# Generated by Django 5.2.4 on 2025-07-12 13:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Suggested time limit in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_texts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('full_text', 'Full Text'), ('section', 'Section Practice'), ('fill_blanks', 'Fill in the Blanks'), ('speed_challenge', 'Speed Challenge')], default='full_text', max_length=20)),
                ('words_practiced', models.PositiveIntegerField(default=0)),
                ('words_correct', models.PositiveIntegerField(default=0)),
                ('accuracy_percentage', models.FloatField(default=0.0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('words_per_minute', models.PositiveIntegerField(default=150)),
                ('mastery_level_used', models.PositiveIntegerField(default=0)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='session_audio/')),
                ('transcription', models.TextField(blank=True)),
                ('differences', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorization.text')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DelayedRecallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_minutes', models.PositiveIntegerField(default=15)),
                ('reveal_percentage', models.FloatField(default=0.3)),
                ('auto_hide_enabled', models.BooleanField(default=True)),
                ('auto_hide_delay', models.PositiveIntegerField(default=5)),
                ('words_to_recall', models.JSONField(default=list)),
                ('initial_study_time', models.PositiveIntegerField(default=0)),
                ('recall_attempts', models.PositiveIntegerField(default=0)),
                ('successful_recalls', models.PositiveIntegerField(default=0)),
                ('is_study_phase', models.BooleanField(default=True)),
                ('is_waiting_phase', models.BooleanField(default=False)),
                ('is_recall_phase', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('study_started_at', models.DateTimeField(auto_now_add=True)),
                ('recall_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorization.text')),
            ],
            options={
                'ordering': ['-study_started_at'],
            },
        ),
        migrations.CreateModel(
            name='WordRevealSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reveal_strategy', models.CharField(choices=[('progressive', 'Progressive Reveal'), ('mastery_based', 'Mastery-Based Hiding'), ('random_hide', 'Random Word Hiding'), ('sentence_by_sentence', 'Sentence by Sentence'), ('difficulty_adaptive', 'Difficulty Adaptive')], default='progressive', max_length=30)),
                ('reveal_percentage', models.FloatField(default=0.1)),
                ('increment_percentage', models.FloatField(default=0.1)),
                ('auto_hide_enabled', models.BooleanField(default=True)),
                ('hide_delay_seconds', models.PositiveIntegerField(default=3)),
                ('fade_duration_seconds', models.PositiveIntegerField(default=2)),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('currently_visible_words', models.JSONField(default=list)),
                ('mastered_words', models.JSONField(default=list)),
                ('problem_words', models.JSONField(default=list)),
                ('total_rounds_completed', models.PositiveIntegerField(default=0)),
                ('total_practice_time', models.PositiveIntegerField(default=0)),
                ('average_accuracy_per_round', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_round_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorization.text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('word_sequence', 'Word Sequence Difficulty'), ('sentence_start', 'Sentence Start Problems'), ('paragraph_transition', 'Paragraph Transition Issues'), ('long_words', 'Long Word Difficulty'), ('similar_words', 'Similar Word Confusion'), ('rapid_sequence', 'Rapid Sequence Challenge')], max_length=50)),
                ('start_word_index', models.PositiveIntegerField()),
                ('end_word_index', models.PositiveIntegerField()),
                ('difficulty_score', models.FloatField(default=0.0)),
                ('frequency_encountered', models.PositiveIntegerField(default=1)),
                ('context_words', models.JSONField(default=list)),
                ('common_errors', models.JSONField(default=list)),
                ('practice_attempts', models.PositiveIntegerField(default=0)),
                ('successful_completions', models.PositiveIntegerField(default=0)),
                ('average_time_spent', models.FloatField(default=0.0)),
                ('first_identified', models.DateTimeField(auto_now_add=True)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorization.text')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'text'], name='memorizatio_user_id_9eb41b_idx'), models.Index(fields=['difficulty_score'], name='memorizatio_difficu_1356e9_idx'), models.Index(fields=['pattern_type'], name='memorizatio_pattern_a1f043_idx')],
                'unique_together': {('user', 'text', 'pattern_type', 'start_word_index')},
            },
        ),
        migrations.CreateModel(
            name='TextSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('paragraph', 'Paragraph'), ('sentence', 'Sentence'), ('verse', 'Verse'), ('custom', 'Custom')], default='paragraph', max_length=20)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('start_position', models.PositiveIntegerField()),
                ('end_position', models.PositiveIntegerField()),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='memorization.text')),
            ],
            options={
                'ordering': ['text', 'order'],
                'unique_together': {('text', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserTextProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_mastery_percentage', models.FloatField(default=0.0)),
                ('words_mastered', models.PositiveIntegerField(default=0)),
                ('total_practice_time', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('best_accuracy', models.FloatField(default=0.0)),
                ('average_accuracy', models.FloatField(default=0.0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('preferred_words_per_minute', models.PositiveIntegerField(default=150)),
                ('preferred_session_duration', models.PositiveIntegerField(default=300)),
                ('first_practiced', models.DateTimeField(auto_now_add=True)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorization.text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'text')},
            },
        ),
        migrations.CreateModel(
            name='WordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(default='', max_length=100)),
                ('word_index', models.PositiveIntegerField(default=0)),
                ('mastery_level', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('times_practiced', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('repetition', models.PositiveIntegerField(default=0)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('next_review', models.DateTimeField(auto_now_add=True)),
                ('is_problem_word', models.BooleanField(default=False)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('needs_review', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorization.text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'text'], name='memorizatio_user_id_0ba4e5_idx'), models.Index(fields=['next_review'], name='memorizatio_next_re_45b1df_idx'), models.Index(fields=['mastery_level'], name='memorizatio_mastery_f68b91_idx'), models.Index(fields=['is_problem_word'], name='memorizatio_is_prob_062135_idx'), models.Index(fields=['needs_review'], name='memorizatio_needs_r_f637bb_idx')],
                'unique_together': {('user', 'text', 'word_index')},
            },
        ),
    ]
