# Generated by Django 5.2.4 on 2025-07-12 02:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Suggested time limit in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_texts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('full_text', 'Full Text'), ('section', 'Section Practice'), ('fill_blanks', 'Fill in the Blanks'), ('speed_challenge', 'Speed Challenge')], default='full_text', max_length=20)),
                ('words_practiced', models.PositiveIntegerField(default=0)),
                ('words_correct', models.PositiveIntegerField(default=0)),
                ('accuracy_percentage', models.FloatField(default=0.0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('words_per_minute', models.PositiveIntegerField(default=150)),
                ('mastery_level_used', models.PositiveIntegerField(default=0)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='session_audio/')),
                ('transcription', models.TextField(blank=True)),
                ('differences', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorization.text')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TextSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('paragraph', 'Paragraph'), ('sentence', 'Sentence'), ('verse', 'Verse'), ('custom', 'Custom')], default='paragraph', max_length=20)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('start_position', models.PositiveIntegerField()),
                ('end_position', models.PositiveIntegerField()),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='memorization.text')),
            ],
            options={
                'ordering': ['text', 'order'],
                'unique_together': {('text', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserTextProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_mastery_percentage', models.FloatField(default=0.0)),
                ('words_mastered', models.PositiveIntegerField(default=0)),
                ('total_practice_time', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('best_accuracy', models.FloatField(default=0.0)),
                ('average_accuracy', models.FloatField(default=0.0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('preferred_words_per_minute', models.PositiveIntegerField(default=150)),
                ('preferred_session_duration', models.PositiveIntegerField(default=300)),
                ('first_practiced', models.DateTimeField(auto_now_add=True)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorization.text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'text')},
            },
        ),
        migrations.CreateModel(
            name='WordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('word_position', models.PositiveIntegerField()),
                ('easiness_factor', models.FloatField(default=2.5)),
                ('repetition', models.PositiveIntegerField(default=0)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('next_review', models.DateTimeField()),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('correct_attempts', models.PositiveIntegerField(default=0)),
                ('mastery_level', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorization.text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'text'], name='memorizatio_user_id_0ba4e5_idx'), models.Index(fields=['next_review'], name='memorizatio_next_re_45b1df_idx'), models.Index(fields=['mastery_level'], name='memorizatio_mastery_f68b91_idx')],
                'unique_together': {('user', 'text', 'word', 'word_position')},
            },
        ),
    ]
